# ---------------------------------------------------------------------------
# HTTP
# ---------------------------------------------------------------------------
quarkus.http.port=8080

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
quarkus.log.level=INFO
quarkus.log.category."io.jchateau".level=DEBUG
